//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCCTestProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class northwndEntities1 : DbContext
    {
        public northwndEntities1()
            : base("name=northwndEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<EmployeeGetList_Result> EmployeeGetList(Nullable<bool> active)
        {
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeGetList_Result>("EmployeeGetList", activeParameter);
        }

        public System.Data.Entity.DbSet<NCCTestProject.Models.EmployeeGetList_Result> EmployeeGetList_Result { get; set; }
    }
}
